//  ChordProGoldenTests.swift
//  OrainCoreTests
//
//  Proves the Swift ChordPro engine behaves identically to the JavaScript one
//  that has been running on the Pi since Phase 4.
//
//  HOW THIS WORKS
//  --------------
//  `tools/generate_goldens.mjs` runs the real chord.js over a corpus of inputs
//  and writes every expected output to Fixtures/chordpro-goldens.json. These
//  tests load that file and assert the Swift port produces the same answers.
//  Neither implementation is "the spec" in the abstract — the JS is the spec,
//  because that is what has been rendering Callum's songs correctly for
//  months, and a song that renders differently on the phone is a bug even if
//  the phone is arguably more correct.
//
//  If a test here fails, the question is always "did the port drift, or did
//  chord.js change?" — never "should I edit the fixture?". Fixtures are
//  regenerated by running the generator, never by hand.
//
//  Run from the Terminal on the Mac:
//      cd ~/orain-ios/OrainCore && swift test

import XCTest
@testable import OrainCore

// MARK: - Fixture shapes

private struct Goldens: Decodable {
    let parseChordProLine: [LineCase]
    let parseDirectiveLine: [DirectiveCase]
    let buildDirectiveLine: [BuildCase]
    let getSections: [SectionsCase]
    let hasChorus: [BoolCase]
    let repeatChorus: [StringCase]
    let lyricsToEditor: [EditorCase]
    let editorToLyrics: [MergeCase]
    let roundTrip: [RoundTripCase]

    struct Segment: Decodable, Equatable {
        let chord: String?
        let text: String
    }
    struct LineCase: Decodable {
        let input: String
        let expected: [Segment]
    }
    struct DirectiveDTO: Decodable, Equatable {
        let kind: String
        let boundary: String
        let label: String?
    }
    struct DirectiveCase: Decodable {
        let input: String
        let expected: DirectiveDTO?
    }
    struct BuildCase: Decodable {
        let kind: String
        let boundary: String
        let label: String?
        let expected: String
    }
    struct SectionDTO: Decodable, Equatable {
        let kind: String
        let label: String?
        let lines: [String]
    }
    struct SectionsCase: Decodable {
        let input: String
        let expected: [SectionDTO]
    }
    struct BoolCase: Decodable {
        let input: String
        let expected: Bool
    }
    struct StringCase: Decodable {
        let input: String
        let expected: String
    }
    struct RowDTO: Decodable, Equatable {
        let chords: String
        let lyric: String
    }
    struct EditorCase: Decodable {
        let input: String
        let expected: [RowDTO]
    }
    struct MergeCase: Decodable {
        let input: [RowDTO]
        let expected: String
    }
    struct RoundTripCase: Decodable {
        let input: String
        let expected: String
        let lossless: Bool
    }
}

// MARK: - Tests

final class ChordProGoldenTests: XCTestCase {

    private static var goldens: Goldens = {
        guard let url = Bundle.module.url(
            forResource: "chordpro-goldens",
            withExtension: "json",
            subdirectory: "Fixtures"
        ) else {
            fatalError("chordpro-goldens.json is missing from the test bundle")
        }
        do {
            let data = try Data(contentsOf: url)
            return try JSONDecoder().decode(Goldens.self, from: data)
        } catch {
            fatalError("Could not read the golden fixtures: \(error)")
        }
    }()

    private var g: Goldens { Self.goldens }

    /// A guard against the fixtures being silently emptied or truncated — a
    /// suite that loads zero cases would otherwise pass triumphantly.
    func testFixturesAreLoaded() {
        XCTAssertGreaterThanOrEqual(g.parseChordProLine.count, 20)
        XCTAssertGreaterThanOrEqual(g.parseDirectiveLine.count, 20)
        XCTAssertGreaterThanOrEqual(g.getSections.count, 19)
        XCTAssertGreaterThanOrEqual(g.roundTrip.count, 19)
    }

    func testParseChordProLine() {
        for c in g.parseChordProLine {
            let actual = ChordPro.parseChordProLine(c.input).map {
                Goldens.Segment(chord: $0.chord, text: $0.text)
            }
            XCTAssertEqual(actual, c.expected, "input: \(debug(c.input))")
        }
    }

    func testParseDirectiveLine() {
        for c in g.parseDirectiveLine {
            let parsed = ChordPro.parseDirectiveLine(c.input)
            let actual = parsed.map {
                Goldens.DirectiveDTO(
                    kind: $0.kind.rawValue,
                    boundary: $0.boundary.rawValue,
                    label: $0.label
                )
            }
            XCTAssertEqual(actual, c.expected, "input: \(debug(c.input))")
        }
    }

    func testBuildDirectiveLine() {
        for c in g.buildDirectiveLine {
            guard let kind = SectionKind(rawValue: c.kind),
                  let boundary = Boundary(rawValue: c.boundary)
            else {
                XCTFail("fixture has an unknown kind/boundary: \(c.kind)/\(c.boundary)")
                continue
            }
            let actual = ChordPro.buildDirectiveLine(
                kind: kind, boundary: boundary, label: c.label
            )
            XCTAssertEqual(actual, c.expected, "\(c.kind)/\(c.boundary)/\(debug(c.label ?? "nil"))")
        }
    }

    func testGetSections() {
        for c in g.getSections {
            let actual = ChordPro.getSections(c.input).map {
                Goldens.SectionDTO(kind: $0.kind.rawValue, label: $0.label, lines: $0.lines)
            }
            XCTAssertEqual(actual, c.expected, "input: \(debug(c.input))")
        }
    }

    func testHasChorus() {
        for c in g.hasChorus {
            XCTAssertEqual(
                ChordPro.hasChorus(c.input), c.expected, "input: \(debug(c.input))"
            )
        }
    }

    func testRepeatChorus() {
        for c in g.repeatChorus {
            XCTAssertEqual(
                ChordPro.repeatChorus(c.input), c.expected, "input: \(debug(c.input))"
            )
        }
    }

    func testLyricsToEditor() {
        for c in g.lyricsToEditor {
            let actual = ChordPro.lyricsToEditor(c.input).map {
                Goldens.RowDTO(chords: $0.chords, lyric: $0.lyric)
            }
            XCTAssertEqual(actual, c.expected, "input: \(debug(c.input))")
        }
    }

    func testEditorToLyrics() {
        for c in g.editorToLyrics {
            let rows = c.input.map { EditorRow(chords: $0.chords, lyric: $0.lyric) }
            XCTAssertEqual(
                ChordPro.editorToLyrics(rows), c.expected, "input: \(c.input)"
            )
        }
    }

    /// The guarantee that makes the editor safe: loading a song and saving it
    /// unchanged must reproduce the stored text byte for byte. Recorded as
    /// goldens rather than asserted directly, so that if the JS is ever lossy
    /// for some input, the Swift port is lossy in exactly the same way instead
    /// of "fixing" it into a divergence.
    func testRoundTripMatchesJavaScript() {
        for c in g.roundTrip {
            let actual = ChordPro.editorToLyrics(ChordPro.lyricsToEditor(c.input))
            XCTAssertEqual(actual, c.expected, "input: \(debug(c.input))")
            if c.lossless {
                XCTAssertEqual(actual, c.input, "should be lossless: \(debug(c.input))")
            }
        }
    }

    // MARK: Edge cases the corpus cannot express in JSON

    func testNilInputsAreSafe() {
        XCTAssertEqual(ChordPro.getSections(nil), [])
        XCTAssertFalse(ChordPro.hasChorus(nil))
        XCTAssertEqual(ChordPro.repeatChorus(nil), "")
        XCTAssertEqual(ChordPro.lyricsToEditor(nil), [EditorRow(chords: "", lyric: "")])
    }

    private func debug(_ s: String) -> String {
        "\"\(s.replacingOccurrences(of: "\n", with: "\\n"))\""
    }
}
