//  ChordPro.swift
//  OrainCore
//
//  A faithful Swift port of the Òrain web app's `static/chord.js`.
//
//  WHY A PORT AND NOT A REWRITE
//  ---------------------------
//  The Pi app already stores every song as ChordPro inline text, and the
//  round-trip guarantee — editorToLyrics(lyricsToEditor(L)) == L — is what
//  keeps a load-then-save from quietly rewriting a song. If the iOS app
//  parsed or re-emitted that text even slightly differently, editing a song
//  on the phone would produce a file the Pi app renders differently. So this
//  is a deliberate line-by-line port, quirks included, not an improvement.
//
//  Every function here is checked against golden fixtures generated by
//  running the real chord.js (see tools/generate_goldens.mjs). If you change
//  behaviour here on purpose, regenerate the fixtures from the changed
//  chord.js — never edit the fixtures by hand.
//
//  ONE KNOWN DIVERGENCE, DOCUMENTED
//  --------------------------------
//  JavaScript string indices are UTF-16 code units; Swift's are Characters
//  (grapheme clusters). For all text this app actually holds — Gàidhlig and
//  English in normal precomposed (NFC) form — the two agree exactly. They
//  would disagree for astral-plane characters (emoji) or decomposed accents,
//  where JS counts 2 units and Swift counts 1. Chord alignment in those cases
//  would shift by a column. Chosen deliberately: Characters are the correct
//  unit for "which syllable does this chord sit over", and the alternative
//  (counting UTF-16 units) would misalign visually for the same input. Noted
//  so nobody later "fixes" it without knowing it was a decision.

import Foundation

// MARK: - Types

/// One run of lyric text and the chord (if any) that sounds at its start.
public struct ChordSegment: Equatable, Codable, Sendable {
    public let chord: String?
    public let text: String

    public init(chord: String?, text: String) {
        self.chord = chord
        self.text = text
    }
}

/// The kinds of block a song can be divided into.
/// `plain` is the synthetic kind for lines outside any directive.
public enum SectionKind: String, Equatable, Codable, Sendable {
    case plain
    case chorus
    case verse
    case bridge
}

/// Whether a directive opens or closes a section.
public enum Boundary: String, Equatable, Codable, Sendable {
    case start
    case end
}

/// A parsed `{start_of_chorus: Sèist}`-style line.
public struct Directive: Equatable, Sendable {
    public let kind: SectionKind
    public let boundary: Boundary
    /// The optional label after the colon. `nil` when there was no colon or
    /// the value was empty; `""` when the value was whitespace only — the
    /// same distinction the JavaScript draws.
    public let label: String?

    public init(kind: SectionKind, boundary: Boundary, label: String?) {
        self.kind = kind
        self.boundary = boundary
        self.label = label
    }
}

/// A block of lines, with the kind and label of the directive that opened it.
public struct LyricSection: Equatable, Sendable {
    public let kind: SectionKind
    public let label: String?
    public let lines: [String]

    public init(kind: SectionKind, label: String?, lines: [String]) {
        self.kind = kind
        self.label = label
        self.lines = lines
    }
}

/// One row of the two-line editor: a chord line above a lyric line.
public struct EditorRow: Equatable, Sendable {
    public var chords: String
    public var lyric: String

    public init(chords: String, lyric: String) {
        self.chords = chords
        self.lyric = lyric
    }
}

// MARK: - The engine

public enum ChordPro {

    // MARK: Inline chord parsing

    /// Parse one line of ChordPro-inline lyrics into segments.
    ///
    /// `"[G]Ailein [D]duinn"` becomes
    /// `[(G, "Ailein "), (D, "duinn")]`.
    ///
    /// Mirrors the JS regex `/\[([^\]]+)\]/g`: a bracket pair with at least
    /// one character inside and no nested `]`. An unclosed `[` or an empty
    /// `[]` is ordinary lyric text, not a chord.
    public static func parseChordProLine(_ line: String) -> [ChordSegment] {
        let chars = Array(line)
        var segments: [ChordSegment] = []
        var lastEnd = 0
        var currentChord: String?
        var i = 0

        while i < chars.count {
            guard chars[i] == "[" else {
                i += 1
                continue
            }

            // Find the closing bracket. `[^\]]+` means the content must be
            // non-empty and cannot itself contain `]`.
            var j = i + 1
            while j < chars.count, chars[j] != "]" { j += 1 }

            guard j < chars.count, j > i + 1 else {
                // No closing bracket, or `[]` with nothing inside — the JS
                // regex finds no match here and scanning simply moves on.
                i += 1
                continue
            }

            let matchIndex = i
            let chord = String(chars[(i + 1)..<j])

            if matchIndex > lastEnd || currentChord != nil {
                segments.append(
                    ChordSegment(
                        chord: currentChord,
                        text: String(chars[lastEnd..<matchIndex])
                    )
                )
            }

            currentChord = chord
            lastEnd = j + 1
            i = j + 1
        }

        if lastEnd < chars.count || currentChord != nil {
            segments.append(
                ChordSegment(chord: currentChord, text: String(chars[lastEnd...]))
            )
        }

        return segments
    }

    // MARK: Section directives

    /// The directive names the app recognises, long form and shorthand.
    private static let directiveMap: [String: (SectionKind, Boundary)] = [
        "start_of_chorus": (.chorus, .start),
        "end_of_chorus":   (.chorus, .end),
        "start_of_verse":  (.verse,  .start),
        "end_of_verse":    (.verse,  .end),
        "start_of_bridge": (.bridge, .start),
        "end_of_bridge":   (.bridge, .end),
        "soc": (.chorus, .start),
        "eoc": (.chorus, .end),
        "sov": (.verse,  .start),
        "eov": (.verse,  .end),
        "sob": (.bridge, .start),
        "eob": (.bridge, .end),
    ]

    /// Parse a directive line such as `{start_of_verse: Verse 2}` or `{soc}`.
    ///
    /// Returns `nil` for anything that is not a recognised directive — including
    /// unknown directives like `{title: …}`, which are treated as ordinary
    /// lyric text (exactly as the web app does).
    ///
    /// Hand-written rather than regex-driven so it cannot drift on a regex
    /// dialect difference. It reproduces `^\s*\{([^}:]+)(?::([^}]*))?\}\s*$`:
    /// optional surrounding whitespace, a brace pair, a key containing neither
    /// `}` nor `:`, and an optional `:value` whose value contains no `}`.
    public static func parseDirectiveLine(_ line: String) -> Directive? {
        let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.count >= 2,
              trimmed.hasPrefix("{"),
              trimmed.hasSuffix("}")
        else { return nil }

        let inner = String(trimmed.dropFirst().dropLast())

        let key: String
        let rawValue: String?

        if let colon = inner.firstIndex(of: ":") {
            key = String(inner[inner.startIndex..<colon])
            rawValue = String(inner[inner.index(after: colon)...])
        } else {
            key = inner
            rawValue = nil
        }

        // `[^}:]+` — the key must be non-empty and free of braces.
        guard !key.isEmpty, !key.contains("}") else { return nil }
        // `[^}]*` — the value, if present, must be free of braces.
        if let value = rawValue, value.contains("}") { return nil }

        guard let entry = directiveMap[key.trimmingCharacters(in: .whitespaces).lowercased()]
        else { return nil }

        // JS: `m[2] ? m[2].trim() : null`. An absent group and an empty
        // string are both falsy, so both give nil; a whitespace-only value is
        // truthy and trims to "".
        let label: String?
        if let value = rawValue, !value.isEmpty {
            label = value.trimmingCharacters(in: .whitespaces)
        } else {
            label = nil
        }

        return Directive(kind: entry.0, boundary: entry.1, label: label)
    }

    /// Build the canonical long-form directive line for storage.
    ///
    /// An empty or whitespace-only label is dropped, giving `{start_of_verse}`.
    public static func buildDirectiveLine(
        kind: SectionKind,
        boundary: Boundary,
        label: String? = nil
    ) -> String {
        let name = "\(boundary.rawValue)_of_\(kind.rawValue)"
        if let label,
           !label.trimmingCharacters(in: .whitespaces).isEmpty {
            return "{\(name): \(label.trimmingCharacters(in: .whitespaces))}"
        }
        return "{\(name)}"
    }

    /// Split lyrics into sections.
    ///
    /// Lines outside any directive collect into `plain` sections. An empty
    /// lyrics string gives an empty array; a lyrics string with no directives
    /// gives one `plain` section.
    public static func getSections(_ lyrics: String?) -> [LyricSection] {
        guard let lyrics, !lyrics.isEmpty else { return [] }

        var sections: [LyricSection] = []
        var currentKind: SectionKind = .plain
        var currentLabel: String?
        var currentLines: [String] = []

        for line in splitLines(lyrics) {
            guard let d = parseDirectiveLine(line) else {
                currentLines.append(line)
                continue
            }

            if d.boundary == .start {
                // Flush the current section only if it has content.
                if !currentLines.isEmpty {
                    sections.append(
                        LyricSection(kind: currentKind, label: currentLabel, lines: currentLines)
                    )
                }
                currentKind = d.kind
                currentLabel = d.label
                currentLines = []
            } else {
                // An end directive always closes the open section, even empty.
                sections.append(
                    LyricSection(kind: currentKind, label: currentLabel, lines: currentLines)
                )
                currentKind = .plain
                currentLabel = nil
                currentLines = []
            }
        }

        if !currentLines.isEmpty {
            sections.append(
                LyricSection(kind: currentKind, label: currentLabel, lines: currentLines)
            )
        }

        return sections
    }

    // MARK: Auto-repeat chorus

    /// Does this lyric text contain at least one chorus section?
    /// Used to hide the repeat-chorus control for versions it cannot help.
    public static func hasChorus(_ lyrics: String?) -> Bool {
        getSections(lyrics).contains { $0.kind == .chorus }
    }

    /// Return a copy of the lyrics with the chorus repeated after each verse.
    ///
    /// Rules, settled with Callum on 2026-05-29 and preserved here:
    ///   - single-chorus model: the first chorus is the one repeated;
    ///   - skip injection where a chorus already follows that verse;
    ///   - lyrics with no chorus come back untouched.
    ///
    /// The stored text is never mutated — this builds a new string that the
    /// renderer consumes as if it had been stored that way.
    public static func repeatChorus(_ lyrics: String?) -> String {
        guard let lyrics, !lyrics.isEmpty else { return "" }

        let sections = getSections(lyrics)

        guard let chorus = sections.first(where: { $0.kind == .chorus }) else {
            return lyrics  // nothing to repeat — return the original verbatim
        }

        func sectionToLines(_ s: LyricSection) -> [String] {
            if s.kind == .plain { return s.lines }
            return [buildDirectiveLine(kind: s.kind, boundary: .start, label: s.label)]
                + s.lines
                + [buildDirectiveLine(kind: s.kind, boundary: .end, label: nil)]
        }

        let chorusLines = sectionToLines(chorus)

        var out: [String] = []
        for (i, s) in sections.enumerated() {
            out.append(contentsOf: sectionToLines(s))

            if s.kind == .verse {
                let next = i + 1 < sections.count ? sections[i + 1] : nil
                let alreadyFollowed = next?.kind == .chorus
                if !alreadyFollowed {
                    out.append(contentsOf: chorusLines)
                }
            }
        }

        return out.joined(separator: "\n")
    }

    // MARK: Two-line editor round-trip

    /// Convert stored ChordPro lyrics into the two-line editor's rows.
    ///
    /// Directive lines pass through as lyric-only rows so they survive an
    /// edit untouched. Blank lines become empty rows.
    public static func lyricsToEditor(_ lyrics: String?) -> [EditorRow] {
        guard let lyrics, !lyrics.isEmpty else {
            return [EditorRow(chords: "", lyric: "")]
        }

        var rows: [EditorRow] = []

        for line in splitLines(lyrics) {
            if parseDirectiveLine(line) != nil {
                rows.append(EditorRow(chords: "", lyric: line))
                continue
            }

            let segs = parseChordProLine(line)

            var chordChars: [Character] = []
            var lyricChars: [Character] = []

            for (i, seg) in segs.enumerated() {
                let pos = lyricChars.count
                if let chord = seg.chord {
                    if chordChars.count < pos {
                        chordChars.append(
                            contentsOf: repeatElement(" ", count: pos - chordChars.count)
                        )
                    }
                    chordChars.append(contentsOf: chord)
                }

                var text = seg.text
                // Only drop the leading spaces of a segment when doing so
                // cannot glue two words together: either it is the first
                // segment, or the previous segment already ended in
                // whitespace.
                let prev = i > 0 ? segs[i - 1] : nil
                let safe = (i == 0) || (prev?.text.last?.isWhitespace ?? false)
                if safe {
                    while text.first == " " { text.removeFirst() }
                }
                lyricChars.append(contentsOf: text)
            }

            while let last = chordChars.last, last.isWhitespace {
                chordChars.removeLast()
            }

            rows.append(
                EditorRow(chords: String(chordChars), lyric: String(lyricChars))
            )
        }

        return rows
    }

    /// Convert the editor's rows back into stored ChordPro lyrics.
    ///
    /// The lyric line is authoritative and is never padded, so loading a song
    /// and saving it without edits reproduces the stored text exactly. Chords
    /// positioned past the end of the lyric are appended as trailing markers
    /// rather than being dropped.
    public static func editorToLyrics(_ rows: [EditorRow]) -> String {
        var lines: [String] = []

        for row in rows {
            if parseDirectiveLine(row.lyric) != nil {
                lines.append(row.lyric)
                continue
            }

            if row.chords.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                lines.append(row.lyric)
                continue
            }

            let chords = Array(row.chords)
            let lyric = Array(row.lyric)

            var result = ""
            var i = 0  // position in the chord line
            var j = 0  // position in the lyric line

            while i < chords.count || j < lyric.count {
                if i < chords.count, chords[i] != " " {
                    var chord = ""
                    while i < chords.count, chords[i] != " " {
                        chord.append(chords[i])
                        i += 1
                    }
                    result += "[\(chord)]"
                }

                if j < lyric.count {
                    result.append(lyric[j])
                    j += 1
                    i = max(i, j)  // keep the two cursors in step
                } else {
                    i += 1
                }
            }

            lines.append(result)
        }

        return lines.joined(separator: "\n")
    }

    // MARK: - Helpers

    /// Split on "\n" with JavaScript's semantics: a trailing newline yields a
    /// final empty element, and an empty string yields one empty element.
    /// Swift's `split` drops empty subsequences by default, which would lose
    /// blank lines — the one place a naive port goes wrong silently.
    static func splitLines(_ s: String) -> [String] {
        s.components(separatedBy: "\n")
    }
}
